//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATIS
    {
        public int satısıd { get; set; }
        public Nullable<int> ürün { get; set; }
        public Nullable<int> müsteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual TBL_MUSTERİ TBL_MUSTERİ { get; set; }
        public virtual TBL_URUNLER TBL_URUNLER { get; set; }
    }
}
